### ISSUE TITLE
Nothing appear

### ISSUE THREAD

**Issue by technofab** [thobach/MMM-MicrosoftToDo#1]
I made all like in instruction, but nothin appear on mirror..

Any ideas to check? Pay attention that I use the module from a remote server in cloud.

**Comment by thobach** [comment]
I'm sorry, I think I missed a configuration to disable CORS, which I had already present from a different plugin. I updated the readme of https://github.com/thobach/MMM-MicrosoftToDo with step 3 to disable CORS in the config file. Please let me know if it works now, thanks!

**Comment by technofab** [comment]
Hi, I add the code like this: https://forum.magicmirror.builders/topic/9222/mmm-nest-status-new-module-for-your-nest-thermostats-and-protect-smoke-detectors/25# but nothing appears, only the title works.

I also do configuration for localhost and for the remote server hostname too...

**Comment by Dysantic** [comment]
Hi Thomas, thanks for your work on this module! With regards to disabling webSecurity in Electron, are there any other alternative options?

https://electronjs.org/docs/tutorial/security#5-do-not-disable-websecurity

I know that a Magic Mirror isn't production in the "facing the internet" sense, but considering the open nature of the project and the numerous modules available, I'm somewhat concerned about intentionally relaxing security on a device that resides within my network.

Thanks again!

**Comment by thobach** [comment]
I moved the API requests to node_helper to not require CORS to be disabled.
