### ISSUE TITLE
Black Screen 

### ISSUE THREAD

**Issue by Themaster312** [thobach/MMM-MicrosoftToDo#103]
I have a Black Screen After install

**Comment by Johan-Claesson** [comment]
I think you need to downgrade MM to V2.24.0: see my issue https://github.com/thobach/MMM-MicrosoftToDo/issues/104

**Comment by thobach** [comment]
I addressed the issue of https://github.com/thobach/MMM-MicrosoftToDo/issues/104, please try it with the latest commit. Thanks!
