### ISSUE TITLE
does it work on MagicMirror2?

### ISSUE THREAD

**Issue by natalie2oo3** [thobach/MMM-MicrosoftToDo#105]
I installed it but MM2 turned black screen on launch.

**Comment by thobach** [comment]
What logs related to the module (incl. error messages) do you see in the Magic Mirror logs (console output when you launch the Magic Mirror via npm run start) and console logs (ctrl + shift + i -> Console)?

You can try also to remove all modules but this one in the config file to rule out it is any other module causing the issue.
