### ISSUE TITLE
"Failed to load swrast driver"

### ISSUE THREAD

**Issue by ambernagel** [thobach/MMM-MicrosoftToDo#108]
I'm getting a "failed to load swrast driver" when I add this to my mirror. This has happened since the last update, does anyone know how to fix it? It was working fine before.

**Comment by thobach** [comment]
Is this issue still present? Does the mirror work fine without this module, but fails once it is added only, as well as when only this module is added?

Can you try running `npm install` again from step https://github.com/thobach/MMM-MicrosoftToDo#installation?
