### ISSUE TITLE
Loading entries 

### ISSUE THREAD

**Issue by macbenoit** [thobach/MMM-MicrosoftToDo#11]
Hello do you know why i have this message please ?

**Comment by feverlabs** [comment]
> Hello do you know why i have this message please ?

You need to follow the instructions at the bottom, and disable electron web security.

**Comment by thobach** [comment]
With the latest version disabling electron web security is not needed anymore.
Do you still have the issue? Maybe the configuration parameters are incorrect, I suggest to check logs to see if you have any related error message.

**Comment by macbenoit** [comment]
I dis the électron desactivation but still havé the problème, where can i see the logs plz?

**Comment by thobach** [comment]
With the latest update of the module you don't need the electron web security deactivation.
Please navigate to the "MagicMirror/modules/MMM-MicrosoftToDo" folder, run "git pull" and then restart and show server side logs e.g. with "pm2 stop mm && pm2 start mm && pm2 logs mm".
If you open the Magic Mirror in your browser, e.g. "http://192.168.0.15:8080" (depending on your local IP), you can see the logs with "Command+Option+J" (Chrome macOS), or "Control+Shift+J" (Chrome Windows/Linux).

**Comment by macbenoit** [comment]
Hello thank you so much it works great just after the git pull, can you explain it to me ?

**Comment by JulianoSGomes** [comment]
I had this problem using **_task list ID_** from a list created by the Web [https://to-do.microsoft.com/ ](https://to-do.microsoft.com/) , generating a short url like   

>  .../tasks/l-1x7n370onxl

 so i created a list through "Microsoft To Do, Android app" and it's generated a long url like 

> .../tasks/AQMkADAwATZiZmYAZC1kMjE2LTIwNzMtMDACLTAwCgAuAAADgek7Jnf5y06rGrH3CR07ygEAoS5yi6HuqEmGF7U_zbAvGwADU_ndfAAAAA==

using **_task list ID_** from longest url, i solved my problem.

**Comment by sgarg15** [comment]
Hey, so i did everything and i am having this issue, i tried git pull as well and it says that its already up to date does anyone know why?

**Comment by ClausMunch** [comment]
I'm also unable to load the list. I get this in my Chrome log:
`MM-MicrosoftToDo.js:20 Uncaught (in promise) TypeError: Cannot read property 'length' of null
    at Class.getDom (MMM-MicrosoftToDo.js:20)
    at main.js:111
    at new Promise (<anonymous>)
    at updateDom (main.js:110)
    at Object.updateDom (main.js:520)
    at Class.updateDom (module.js:358)
    at Class.socketNotificationReceived (MMM-MicrosoftToDo.js:61)
    at module.js:246
    at r.<anonymous> (socketclient.js:30)
    at r.emit (index.js:83)
    at r.onevent (index.js:83)
    at r.MMSocket.self.socket.onevent (socketclient.js:24)
    at r.onpacket (index.js:83)
    at r.<anonymous> (index.js:83)
    at r.emit (index.js:83)
    at r.ondecoded (index.js:83)
    at a.<anonymous> (index.js:83)
    at a.r.emit (index.js:83)
    at a.add (index.js:83)
    at r.ondata (index.js:83)
    at r.<anonymous> (index.js:83)
    at r.emit (index.js:83)
    at r.onPacket (index.js:83)
    at r.<anonymous> (index.js:83)
    at r.emit (index.js:83)
    at r.onPacket (index.js:83)
    at r.onData (index.js:83)
    at WebSocket.ws.onmessage (index.js:83)
getDom @ MMM-MicrosoftToDo.js:20
(anonymous) @ main.js:111
updateDom @ main.js:110
updateDom @ main.js:520
updateDom @ module.js:358
socketNotificationReceived @ MMM-MicrosoftToDo.js:61
(anonymous) @ module.js:246
(anonymous) @ socketclient.js:30
r.emit @ index.js:83
r.onevent @ index.js:83
MMSocket.self.socket.onevent @ socketclient.js:24
r.onpacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.ondecoded @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
a.add @ index.js:83
r.ondata @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
r.onData @ index.js:83
ws.onmessage @ index.js:83`

**Comment by mirko3000** [comment]
Same for me, followed the exact procedure, but it seems not to load the list. Even if I ommit the listId, it gives me a different error in node_helper, also it seems not to retrieve any list.

Any idea?

**Comment by mirko3000** [comment]
Ok, after debugging the REST response I got the issue:
"MailboxNotEnabledForRESTAPI" - REST API is not yet supported for this mailbox. 

So it seems this approach only works for Office365 accounts - I am using an old outlook.com account.

**Comment by thobach** [comment]
I fixed the error logging for invalid configuration parameter. Could you please navigate to `~/MagicMirror/modules/MMM-MicrosoftToDo` and perform a `git pull`, restart the Magic Mirror and let me know wich error messages you are seeing now? Thanks!

**Comment by codingwatermelon** [comment]
hey there, having the same issue (stuck on Loading Entries...) but nothing related to this module is showing up in the console log (I am currently up to date as of 4/28)

**Comment by thobach** [comment]
Based on no more updates about this issue appearing, I'm closing the issue for now. Please reopen with the error message you see if the issue still persists, thanks!
