### ISSUE TITLE
Not showing tasks

### ISSUE THREAD

**Issue by Entropy159** [thobach/MMM-MicrosoftToDo#111]
Recently this module just stopped working. I didn't do anything to my magic mirror, but I think it has something to do with the new grid layout they added to the website. Now it just shows a single checkbox with no text and it doesn't load or anything.

**Comment by alejandrogonzalez01** [comment]
Same here.... moved to a new house and after about a few months, decided to get the magic mirror out.
Registered a new app, followed documentation, 
Blank List with a checkbox....

Will try to check out logs later throughout the week. Most likely Module will need to be recreated to adopt any backend changes Microsoft has made.

**Comment by dgoth** [comment]
Same issue here. I uninstalled the app. Reinstalled and went through the whole preparation process again. Just have a blank list with a single checkbox.

**Comment by leightonc1** [comment]
Sadly I'm experiencing the same. I'm not certain when it began, but I noticed that existing tasks weren't updating about 2 weeks ago. After restarting MagicMirror2, it looks like tasks have completely stopped loading.

**Comment by thobach** [comment]
I just tried on the latest version of magic mirror (v2.27.0) also with a newly generated app and it still works fine for me.
Does anyone have some server and client logs to help me troubleshoot the issue?
What kind of azure account do you use? A personal one without a dedicated directory?

**Comment by akromm** [comment]
I also have the issue. I'm on MagicMirror 2.27.0 also. 

This is my first time trying to use it so I can't say if it would have worked before.

What kind of information should I collect to help debug this?

[Edit]
I added a bunch of "console.log()" statements to most/all of the methods in MMM-MicrosofToDo.js and node_helper.js and this is the output I get:

![image](https://github.com/thobach/MMM-MicrosoftToDo/assets/87152103/b0fa989b-b115-44dd-85f6-b13ef891f652)

Notably I don't see `socketNotificationReceived`, `socketNotificationReceived`, `getTodos`, `fetchList` or other methods being called.

[Edit 2]
After restarting the hardware the tasks started showing up.

**Comment by leightonc1** [comment]
The issue has persisted for me. I checked my logs today and found the following error. 

Update 1: I have done the following troubleshooting: rebooted hardware, created new app registration(inc. client id, secret, refresh token). The error stays the same.

Update 2: I just wasn't patient enough. Creating a new app registration worked! Here are the steps I took to resolve:
1. Created a new app registration, client id, refresh token, etc. 
2. Updated config.js with new client ID, refresh token, and secret
3. Restarted MagicMirror
4. Waited 5 minutes

After checking previous issues it may have been possible to fix only by creating a new refresh token, but I can't test that now.

Error:
```
0|MagicMirror  | [2024-06-08 23:09:04.032] [ERROR] Response {
0|MagicMirror  |   [Symbol(realm)]: null,
0|MagicMirror  |   [Symbol(state)]: {
0|MagicMirror  |     aborted: false,
0|MagicMirror  |     rangeRequested: false,
0|MagicMirror  |     timingAllowPassed: true,
0|MagicMirror  |     requestIncludesCredentials: true,
0|MagicMirror  |     type: 'default',
0|MagicMirror  |     status: 400,
0|MagicMirror  |     timingInfo: {
0|MagicMirror  |       startTime: 12525957.657261014,
0|MagicMirror  |       redirectStartTime: 0,
0|MagicMirror  |       redirectEndTime: 0,
0|MagicMirror  |       postRedirectStartTime: 12525957.657261014,
0|MagicMirror  |       finalServiceWorkerStartTime: 0,
0|MagicMirror  |       finalNetworkResponseStartTime: 0,
0|MagicMirror  |       finalNetworkRequestStartTime: 0,
0|MagicMirror  |       endTime: 0,
0|MagicMirror  |       encodedBodySize: 508,
0|MagicMirror  |       decodedBodySize: 508,
0|MagicMirror  |       finalConnectionTimingInfo: null
0|MagicMirror  |     },
0|MagicMirror  |     cacheState: '',
0|MagicMirror  |     statusText: 'Bad Request',
0|MagicMirror  |     headersList: HeadersList {
0|MagicMirror  |       cookies: [Array],
0|MagicMirror  |       [Symbol(headers map)]: [Map],
0|MagicMirror  |       [Symbol(headers map sorted)]: null
0|MagicMirror  |     },
0|MagicMirror  |     urlList: [ [URL] ],
0|MagicMirror  |     body: { stream: undefined }
0|MagicMirror  |   },
0|MagicMirror  |   [Symbol(headers)]: HeadersList {
0|MagicMirror  |     cookies: [
0|MagicMirror  |       'fpc=[OBFUSCATED]; expires=Tue, 09-Jul-2024 06:09:03 GMT; path=/; secure; HttpOnly; SameSite=None',
0|MagicMirror  |       'x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly',
0|MagicMirror  |       'stsservicecookie=estsfd; path=/; secure; samesite=none; httponly'
0|MagicMirror  |     ],
0|MagicMirror  |     [Symbol(headers map)]: Map(14) {
0|MagicMirror  |       'cache-control' => [Object],
0|MagicMirror  |       'pragma' => [Object],
0|MagicMirror  |       'content-type' => [Object],
0|MagicMirror  |       'expires' => [Object],
0|MagicMirror  |       'strict-transport-security' => [Object],
0|MagicMirror  |       'x-content-type-options' => [Object],
0|MagicMirror  |       'p3p' => [Object],
0|MagicMirror  |       'x-ms-request-id' => [Object],
0|MagicMirror  |       'x-ms-ests-server' => [Object],
0|MagicMirror  |       'x-ms-srs' => [Object],
0|MagicMirror  |       'x-xss-protection' => [Object],
0|MagicMirror  |       'set-cookie' => [Object],
0|MagicMirror  |       'date' => [Object],
0|MagicMirror  |       'content-length' => [Object]
0|MagicMirror  |     },
0|MagicMirror  |     [Symbol(headers map sorted)]: null
0|MagicMirror  |   }
0|MagicMirror  | } 
0|MagicMirror  | [2024-06-08 23:09:04.039] [ERROR] [MMM-MicrosoftToDo]: getTodos / get access token: https://login.microsoftonline.com/common/oauth2/v2.0/token 
0|MagicMirror  | [2024-06-08 23:09:04.040] [ERROR] [MMM-MicrosoftToDo]: Error: checkFetchStatus failed with status 'Bad Request' {} 
```

**Comment by Entropy159** [comment]
I was also able to fix this by redoing the setup.
