### ISSUE TITLE
Feature Request: left align and display initials for assigned tasks

### ISSUE THREAD

**Issue by feverlabs** [thobach/MMM-MicrosoftToDo#12]
I use the board to organize household todo items, and being able to show the assigned user initial is fairly important to me, similar to how the old Wunderlist module handled it.

If I get some time I'll take a whirl at implementing it.

**Comment by thobach** [comment]
It seems the AssignedTo value in their REST API response is always empty. I'm waiting for Microsoft to clarify this first: https://github.com/microsoftgraph/microsoft-graph-docs/issues/6850.

Would you want to have them displayed like: 1) "[FL] Task 1", 2) "FK: Task 1", 3) "FL Task 1" (where FL has a white background and black letters with some padding around, 4) <your idea>?

**Comment by feverlabs** [comment]
I like the look of a different text and/or background. The way it was done in teh old Wunderlist setup was essentially:
<left align>Task 1</la> <right align>FL</ra> with the FL inside a small circle, white fill, black text.

I'm a lot less picky about what it looks like, but pretty is always nice :)

**Comment by thobach** [comment]
Thanks @feverlabs for the heads-up. Unfortunately the AssignedTo value is not exposed through the REST API hence it cannot be retrieved and displayed. Once this is done this issue can be re-opened.
FYI: It seems there may be some support if the assigned person is set through Outlook, but not through Microsoft To Do - https://github.com/microsoftgraph/microsoft-graph-docs/issues/4982.
