### ISSUE TITLE
Feature Request: Due Date

### ISSUE THREAD

**Issue by esmoyer** [thobach/MMM-MicrosoftToDo#14]
I have looked around the documentation so I am guess it's not available, but it would be great to be able to show the due date for the task.

**Comment by esmoyer** [comment]
I was able to figure this out, still learning a lot:

In nodehelper.js I replaced:
`var listUrl = "https://graph.microsoft.com/beta/me/outlook/taskFolders/" + config.listId + "/tasks?$select=subject,status&$top=" + config.itemLimit + "&$filter=status%20ne%20%27completed%27"`

with 

`var listUrl = "https://graph.microsoft.com/beta/me/outlook/taskFolders/" + config.listId + "/tasks?$top=50&$orderby=dueDateTime/dateTime&$filter=status%20ne%20%27completed%27`

This removed the limit of only pulling subject and status and also sorts the list by dueDate.

And then re-wrote this line in MMM-MicrosoftTodo.js

```
  // for each entry add styled list items
      if (this.list.length != 0) {
        this.list.forEach(element => listItemsText += "<li style=\"list-style-position:inside; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;\">" + moment(new Date(element.dueDateTime.dateTime)).format("ddd MMM DD") + " - " + element.subject + "</li>");
```
This solved what I was looking for, hopefully this helps others.

![image](https://user-images.githubusercontent.com/17444085/74096099-d4f11600-4abf-11ea-9f46-302ce10d41e3.png)

**Comment by mojomuffins** [comment]
Worked perfectly for me, thanks a lot!
