### ISSUE TITLE
This module cannot be installed if you dont have wunderlist already. (microsoft takeover)

### ISSUE THREAD

**Issue by Bernard-h** [thobach/MMM-MicrosoftToDo#15]
In many attempt of getting my Alexa-based shopping list on my mirror. I found this great module.
As some of you might know, as per May 2020 wunderlist is gone and it will b microsoft to-do. If you have wunderlist already setting up this module is pretty straightforward. My compliments to the developer. However, I didnt have wunderlist, nor microsoft to do nor a microsoft account on the email adres my alexa(smart home devices) is registered. I went about installing the module. 

I got the module to work. Any items I add from the microsft to do dash are updated on the mirror. Great Suc6! However, when I add items through Alexa to my shopping list... I get a pop up in microsoft to do to start importing wunderlist items. 

Ha you might think , its working. And it probably is however when I start import im prompted to sign in to wunderlist. My account is not known. Ok....lets try opening a wunderlist account so things can start to b imported (trough the enabled alexa skill as mentioned in the readme). 
:( when signing up you get a great: we are moving announcement and all new sign ups are automatically microsoft to do. I even tried the wunderlist app on the phone to see if I can sneak in with creating an old wunderlist account. No suc6.

Does anybody know how to work around this ? My conclusion at this point is that as of now, the module is not suitable for users who do not have wunderlist already. 
Secondly, im kinda curious to see what happens in May 2020 when wunderlist shuts down..

If anybody has an idea on how to get an alexa controlled shopping list displayed on my mirror... please let me know.

**Comment by Tukks** [comment]
Hi,
You can install https://www.amazon.fr/B-Dev-Wonder-Do-It/dp/B07BHLPLGD to sync your Alexa todo list with Microsoft todo and use this module to show the list on your mirror.

Amazon us : https://www.amazon.com/B-Dev-Wonder-Do-It/dp/B07BHLPLGD
Amazon FR : https://www.amazon.fr/B-Dev-Wonder-Do-It/dp/B07BHLPLGD
Just change .fr .com .de for what you needm i think this skill is globally available.
