### ISSUE TITLE
No show on my mirror

### ISSUE THREAD

**Issue by transforpang** [thobach/MMM-MicrosoftToDo#16]
Followed the instructions step by step.

Added module in config.js yet the todo list is now showing for me.

Where could I look to find out what was wrong?

**Comment by thobach** [comment]
Could you solve the issue in the meantime? If not, could you please paste your config.js (with your api keys / secrets / passwords / etc. removed) and the log output from a clean start? E.g. if you use pm2, the files `/home/pi/.pm2/logs/mm-out.log` & `/home/pi/.pm2/logs/mm-error.log`? Thanks!

**Comment by thobach** [comment]
Closing the case for now as there is no response after the latest improvements. Please re-open if the issue still persists.
