### ISSUE TITLE
List sort

### ISSUE THREAD

**Issue by AshDarko** [thobach/MMM-MicrosoftToDo#17]
Hi! Excellent module and great and clear readme instructions by the way thank you!

Not sure if this is an issue, maybe more a query/requets, is it possible to sort the lists? The sorting applied at source (microsoft-todo) doesnt carry through to this list.

Thanks!

**Comment by esmoyer** [comment]
I used the order by parameter in the link, you can find info about it here: https://docs.microsoft.com/en-us/graph/query-parameters#orderby-parameter

I then integrated it into the lisUrl variable in the node.js file of the module:

` var listUrl = "https://graph.microsoft.com/beta/me/outlook/taskFolders/" + config.listId + "/tasks?$top=" + config.itemLimit + "&orderby=dueDateTime/dateTime&$filter=status%20ne%20%27completed%27"`

**Comment by AshDarko** [comment]
Yeah I was just looking for a sort by alpha on each individual list, no worries and thanks for your quick response!

**Comment by thobach** [comment]
Please see https://github.com/thobach/MMM-MicrosoftToDo#installation with the new `orderBy` configuration parameter. You can now sort by `dueDate` or `subject`.
