### ISSUE TITLE
No Response from curl for Refresh Token

### ISSUE THREAD

**Issue by Bauspartakus** [thobach/MMM-MicrosoftToDo#18]
Hi,

I copied the command and changed it according to my values.
When I run the command in the terminal, I get no response...

Am I missing something essential here?

Any help is much appreciated.

**Comment by mchrdk** [comment]
can you post the command you are running(anonymize the secret and ids) and the output? you get either an error, or the json output

**Comment by schnorbi** [comment]
Hello,

I have nearly the same problem, I think, when I am running the command in cmd. What am I doing wrong?

Many thanks for your support in advance!!!
![cmd](https://user-images.githubusercontent.com/64331710/80290664-1bf9b980-8747-11ea-8849-2acd0c961c1a.png)

**Comment by mchrdk** [comment]
> Hello,
> 
> I have nearly the same problem, I think, when I am running the command in cmd. What am I doing wrong?
> 
> Many thanks for your support in advance!!!
> ![cmd](https://user-images.githubusercontent.com/64331710/80290664-1bf9b980-8747-11ea-8849-2acd0c961c1a.png)

windows doesnt play nice with multi line commands like that, either replace the \ at the end of the lines with ^ or remove the \ and the line breaks and have the command be one line in eg. notepad before running

**Comment by schnorbi** [comment]
Hello,

when I am using the code without \ or im using the code with ^ I getting this error.
Many thanks for your support in advance!!!

![cmd](https://user-images.githubusercontent.com/64331710/80302732-28642d80-87ac-11ea-9278-7f99c27ca656.png)

**Comment by zolabus** [comment]
Same problem here....

**Comment by thobach** [comment]
I updated the instructions in https://github.com/thobach/MMM-MicrosoftToDo/blob/master/README.MD#refresh-token-generation-refresh-token to be more Windows friendly, e.g. all in a single line and using double quotes. Could you please try it again with the updated instructions? Thanks!

**Comment by zolabus** [comment]
ok great now it works

**Comment by schnorbi** [comment]
Well done. Thank you for the help of you all. Now it is working very well!!!

;)
