### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by Syngather** [thobach/MMM-MicrosoftToDo#19]
What is the easiest way to adjust the font size of the list and also add some padding to the left side. Still semi new to this. Thank you!

**Comment by thobach** [comment]
I suggest to create a file in the `css` folder named `custom.css` (next to the `main.css` file) and add there for example:
`.MMM-MicrosoftToDo li {
  font-size: 2em;
  line-height: 1.2em;
  padding-left: 1em;
}`
Save the file and refresh or reload the magic mirror.
