### ISSUE TITLE
Getting list ids for "My Day", "Tasks" etc

### ISSUE THREAD

**Issue by williamg97** [thobach/MMM-MicrosoftToDo#2]
Hi,

I've got this working well for normal lists but do you know how I can get it working for "My Day" or the "Tasks" list. There is no hashed "list id" that I can grab from the URL so I'm not sure how to get it as per the instructions. I tried using inbox or myday and it doesnt work. 

Everything else is working great so thanks for the implementation!

**Comment by williamg97** [comment]
Actually I worked this out via manually hitting the API (https://graph.microsoft.com/beta/me/outlook/taskFolders). This gives you the inbox.

Looks like the API doesnt support get "My Day" yet.

**Comment by thobach** [comment]
Thanks for the information about "My Day" not being supported yet. I implemented that the 'Tasks' list is now loaded by default when no listID is provided.
