### ISSUE TITLE
Last Item keeps being displayed even list ist is empty and hideIfEmpty=true

### ISSUE THREAD

**Issue by magic21nrw** [thobach/MMM-MicrosoftToDo#20]
I have a shared list as main list which I share with my wife. The list keeps updating correctly and all items are displayed. I have selected the hideIfEmpty = true in the configuration and when I (or my wife) delete(s) the last item active on the list. It keeps being displayed on the module. The module itself is still visible with the last active item on. I would have expected it to be invisible when no item is active in the shared list.

My Configuration with IDs deleted:

		  {
    module: 'MMM-MicrosoftToDo',
    position: 'top_left',	// This can be any of the regions. Best results in left or right regions.
    header: 'To-Do-Liste', // This is optional
    config: {
      oauth2ClientSecret: 'deleted',
      oauth2RefreshToken: 'deleted',
      oauth2ClientId: 'deleted',
      listId: 'deleted', // optional parameter: default value is the "Tasks" list
      showCheckbox: false, // optional parameter: default value is true and will show a checkbox before each todo list item
      hideIfEmpty: true, // optional parameter: default value is false and will show the module also when the todo list is empty
      maxWidth: 450, // optional parameter: max width in pixel, default value is 450
      itemLimit: 200 // optional parameter: limit on the number of items to show from the list, default value is 200
    }
  },

**Comment by thobach** [comment]
I used your configuration but the issue does not replicate on my side. I also tried it with a shared list and when the last item is removed, the list disappears.

I added a log message in https://github.com/thobach/MMM-MicrosoftToDo/blob/master/MMM-MicrosoftToDo.js#L46 to display the number of items received, that could give us a hint if no more updates are received, or if the logic to hide the module does not work.

Could you please test if the issue is also present when you only display the MMM-MicrosoftToDo module? Maybe there is another module that interferes with the logic to hide the module.

**Comment by magic21nrw** [comment]
Interesting, with the Update, I only get the message that the Plugin is waiting for the items to be receives or Loading list... 

It seems that it now interferes with the MMM-GoogleMapsTraffic Module which did not cause any trouble with the MMM-Wonderlist plugin:

			{
			module: 'MMM-GoogleMapsTraffic',
			position: 'bottom_right',
			config: {
				key: 'Secret',
				updateInterval: 20*60*1000, //20 Minuten
				lat: 48.15,
				lng: 11.556,
				height: '400px',
				width: '500px',
				zoom: 11.6,
				mapTypeId: "roadmap",
				styledMapType: "daniel",
				disableDefaultUI: true,
				backgroundColor: 'hsla(0, 0%, 0%, 0)',
				markers: [
					{
						lat: 11.111,
						lng: 11.111,
						fillColor: '#ff0000'
					},
					{
						lat: 11.111,
						lng: 11.111,
						fillColor: '#a1262d'
					}
				]
			}
		},

If I disable this plugin, the items are loaded properly. The log - does not show any special entries no matter if the MMM-MicrosoftToDo is installed alone or together with the other plugins.

Any Idea - maybe delaying the loading of the plugin for some seconds? The Google Plugin is data heavy - maybe retrieving the map causes some trouble?

**Comment by thobach** [comment]
Could you please try again with the latest version of this module (in the module folder run `git pull` and restart the magic mirror)? I fixed the way messages/errors are logged as the MMM-GoogleMapsTraffic changed some behaviour which made the use of `console.log` not possible anymore (https://github.com/vicmora/MMM-GoogleMapsTraffic/issues/15).
