### ISSUE TITLE
MailboxNotEnabledForRESTAPI - Tasks not loading

### ISSUE THREAD

**Issue by mirko3000** [thobach/MMM-MicrosoftToDo#21]
Hi there,

I started this issue description in another issue already, but after some research I could not find an immediate solution.
The problem for me is that the plugin gives me this error message:

{
  "error": {
    "code": "MailboxNotEnabledForRESTAPI",
    "message": "REST API is not yet supported for this mailbox.",
    "innerError": {
      "request-id": "9d016848-179e-4d1f-99d2-4f04796bf037",
      "date": "2020-04-22T07:36:30"
    }
  }
}

I followed the exact procedure, and I also tested the REST API via the Graph Explorer - here it works just fine. So I guess something inbetween goes wrong, but I have no idea what.

Any ideas?

**Comment by thobach** [comment]
Hi Mirko,
Do you have some more details on your kind of Microsoft account? Is it a personal one or an account managed through Azure Directory?
https://support.microsoft.com/en-us/help/4462988/rest-api-is-not-yet-supported-for-this-mailbox-error has some more details on the problem.

I also adjusted the instructions a bit on https://github.com/thobach/MMM-MicrosoftToDo/blob/master/README.MD as Microsoft change the app registration workflow a bit.

To further trouble shoot the issue it may also be helpful to see if the following command returns an `access token`:
`curl -X POST \
  https://login.microsoftonline.com/common/oauth2/v2.0/token \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'client_id=<client id>&scope=offline_access%20user.read%20tasks.read&refresh_token=<refresh token>&grant_type=refresh_token&client_secret=<client secret>'`

And if that `access token` can be used to get the tasks with the following command:
`curl -X GET \
    'https://graph.microsoft.com/beta/me/outlook/taskFolders/<list id>/tasks?$select=subject,status&$top=10&$filter=status%20ne%20%27completed%27' \
    -H 'Authorization: Bearer <access token>'`

**Comment by mirko3000** [comment]
I am using an umanaged, free Outlook.com Account. Based in the first link I already created a new account - and using the Graph Explorer it works. So REST seems not to be the issue,  rather something with the Tokens. I tried few things, yet nothing resolved the issue...

Will look into your suggestions later!

________________________________
Von: Thomas Bachmann <notifications@github.com>
Gesendet: Sunday, April 26, 2020 3:25:59 PM
An: thobach/MMM-MicrosoftToDo <MMM-MicrosoftToDo@noreply.github.com>
Cc: mirko3000 <mirkoogle@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [thobach/MMM-MicrosoftToDo] MailboxNotEnabledForRESTAPI - Tasks not loading (#21)


Hi Mirko,
Do you have some more details on your kind of Microsoft account? Is it a personal one or an account managed through Azure Directory?
https://support.microsoft.com/en-us/help/4462988/rest-api-is-not-yet-supported-for-this-mailbox-error has some more details on the problem.

I also adjusted the instructions a bit on https://github.com/thobach/MMM-MicrosoftToDo/blob/master/README.MD as Microsoft change the app registration workflow a bit.

To further trouble shoot the issue it may also be helpful to see if the following command returns an access token:
curl -X POST \ https://login.microsoftonline.com/common/oauth2/v2.0/token \ -H 'Content-Type: application/x-www-form-urlencoded' \ -d 'client_id=<client id>&scope=offline_access%20user.read%20tasks.read&refresh_token=<refresh token>&grant_type=refresh_token&client_secret=<client secret>'

And if that access token can be used to get the tasks with the following command:
curl -X GET \ 'https://graph.microsoft.com/beta/me/outlook/taskFolders/<list id>/tasks?$select=subject,status&$top=10&$filter=status%20ne%20%27completed%27' \ -H 'Authorization: Bearer <access token>'

**Comment by mirko3000** [comment]
Tried your two calls:
- Yes I can get both access and refresh tokens
- No the access token still gives me the MailboxNotEnabledForRESTAPI error

Interestingly, if I use the Graph Explorer, I get a different access token. Using that one I can execute the REST call with the above URL...

**Comment by thobach** [comment]
@mirko3000 In that case maybe your configuration of the Magic Mirror Web App in Azure is different from the Graph Explorer app. This is my configuration:
<img width="1439" alt="Bildschirmfoto 2020-05-02 um 10 59 58" src="https://user-images.githubusercontent.com/274056/80859978-f26bf100-8c64-11ea-9036-dfb5b0c26dcb.png">
<img width="664" alt="Bildschirmfoto 2020-05-02 um 11 00 33" src="https://user-images.githubusercontent.com/274056/80859977-f1d35a80-8c64-11ea-85e0-88811d493188.png">
<img width="1289" alt="Bildschirmfoto 2020-05-02 um 11 01 08" src="https://user-images.githubusercontent.com/274056/80859973-ee3fd380-8c64-11ea-8adf-10de363c56a5.png">

If you want, you can share your app manifest from https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/Manifest/appId/<your-app-id>/isMSAApp/true so I can run a diff against mine.

**Comment by mirko3000** [comment]
I noticed a small different at the "Access tokens" checkbox, now I am getting this error:

```
{ code: 'MailboxNotHostedInExchangeOnline',
  message:
   'Mailbox is hosted by an on-premise or non-Exchange server, which is not supported.',
  innerError:
   { 'request-id': '14ea8b84-9aa1-4400-88a9-a1424c67b94e',
     date: '2020-05-02T09:13:19' 
  } 
}
```

After quick research this seems to be a rather new error message. Yes I do not have an exchange account, only Outlook.com. But why it still works in the graph explorer?

**Comment by mirko3000** [comment]
Here is my manifest (IDs changed to 1234567890):
```
{

	"id": "1234567890",
	"acceptMappedClaims": null,
	"accessTokenAcceptedVersion": 2,
	"addIns": [],
	"allowPublicClient": false,
	"appId": "1234567890",
	"appRoles": [],
	"oauth2AllowUrlPathMatching": false,
	"createdDateTime": "2020-04-21T19:12:47Z",
	"groupMembershipClaims": null,
	"identifierUris": [],
	"informationalUrls": {
		"termsOfService": null,
		"support": null,
		"privacy": null,
		"marketing": null
	},
	"keyCredentials": [],
	"knownClientApplications": [],
	"logoUrl": null,
	"logoutUrl": null,
	"name": "MagicMirror",
	"oauth2AllowIdTokenImplicitFlow": false,
	"oauth2AllowImplicitFlow": true,
	"oauth2Permissions": [],
	"oauth2RequirePostResponse": false,
	"optionalClaims": null,
	"orgRestrictions": [],
	"parentalControlSettings": {
		"countriesBlockedForMinors": [],
		"legalAgeGroupRule": "Allow"
	},
	"passwordCredentials": [
		{
			"customKeyIdentifier": null,
			"endDate": "2299-12-30T23:00:00Z",
			"keyId": "1234567890",
			"startDate": "2020-04-26T10:22:06.357Z",
			"value": null,
			"createdOn": "2020-04-26T10:22:07.8474705Z",
			"hint": "=S4",
			"displayName": "MagicMirror"
		}
	],
	"preAuthorizedApplications": [],
	"publisherDomain": null,
	"replyUrlsWithType": [
		{
			"url": "https://localhost:1234",
			"type": "Web"
		}
	],
	"requiredResourceAccess": [
		{
			"resourceAppId": "1234567890",
			"resourceAccess": [
				{
					"id": "1234567890",
					"type": "Scope"
				},
				{
					"id": "1234567890",
					"type": "Scope"
				},
				{
					"id": "1234567890",
					"type": "Scope"
				},
				{
					"id": "1234567890",
					"type": "Scope"
				},
				{
					"id": "1234567890",
					"type": "Scope"
				}
			]
		}
	],
	"samlMetadataUrl": null,
	"signInUrl": null,
	"signInAudience": "AzureADandPersonalMicrosoftAccount",
	"tags": [],
	"tokenEncryptionKeyId": null,
	"verifiedPublisher": {
		"displayName": null,
		"verifiedPublisherId": null,
		"addedDateTime": null
	}
}
```

**Comment by thobach** [comment]
The main differences I see are that for me I have:
* `"allowPublicClient": null,` - according to https://docs.microsoft.com/de-de/azure/active-directory/develop/reference-app-manifest the default value is `false` though, so this should not make a difference
* `resourceAccess` for me lists only one item (e1fe6dd8-ba31-4d61-89e7-88639da4683d -> User.Read), not 5

Maybe this can help with the trouble shooting?

**Comment by mirko3000** [comment]
I experimented with the resources, that is why I have 5. Other than that I have no clue what else to do....
Does it work for you with an Outlook.com account?

**Comment by mirko3000** [comment]
Ok, so I finally got it working! My guess: German data protection laws do not allow REST APIs. I created a new account based in the US, now it works as described.
