### ISSUE TITLE
Module don‘t show up

### ISSUE THREAD

**Issue by atriOo** [thobach/MMM-MicrosoftToDo#22]
Hi,

I followed the guide step by step an added the config but the module don‘t show up. It‘s not even loading a title or something else. 

Here‘s the config. I hope someone can help.

  

> {
>     module: 'MMM-MicrosoftToDo',
>     position: 'top_bar',	// This can be any of the regions. Best results in left or right regions.
>     header: 'Shopping List', // This is optional
>     config: {
>       oauth2ClientSecret: 'deleted',
>       oauth2RefreshToken: 'deleted',
>       oauth2ClientId: 'deleted',
>       listId: 'deleted', // optional parameter: default value is the "Tasks" list
>       showCheckbox: true, // optional parameter: default value is true and will show a checkbox before each todo list item
>       hideIfEmpty: false, // optional parameter: default value is false and will show the module also when the todo list is empty
>       maxWidth: 450, // optional parameter: max width in pixel, default value is 450
>       itemLimit: 200, // optional parameter: limit on the number of items to show from the list, default value is 200
>       orderBy: 'subject', // optional parameter: 'subject' - order results by subject/name, 'dueDate' - order results by due date, default value is unordered
>     }
>   },

**Comment by ottopaulsen** [comment]
I tried to install this today, and got the same problem. I get this error message in the log:
```
'refresh_token' or 'assertion' is not valid.
```
In the example config in the README file it looks like the oauth2ClientSecret is encoded, but the instructions say nothing about that. Can there be something missing in the instructions?

It would be nice with a simpler configuration procedure.

**Comment by ottopaulsen** [comment]
I tried to create a new refresh token, and now it works for me.
@atriOo you have to be very accurate following the config procedure.
Also, try to find error messages in the log (Alt+Cmd+I in the MM window).

**Comment by atriOo** [comment]
Thanks @ottopaulsen for your reply. I‘ve checked the log an found this:

```
MMM-MicrosoftToDo received list of 2 items.
3module.js:198 MMM-MicrosoftToDo is suspended.
```

It seems that it‘s a problem with the module or the config. The authentication works an the Items are updating

**Comment by atriOo** [comment]
Okay. It was a my fault. I also use the MMM-Pages module but instead of using the right class name “MMM-MicrosoftToDo” in the config I forgot the “MMM”. Now the module is showing up correctly. Thanks for the help! :)
