### ISSUE TITLE
Error occurred: ErrorInvalidIdMalformed. Check logs.

### ISSUE THREAD

**Issue by KeramxD** [thobach/MMM-MicrosoftToDo#23]
Hello,
I tried configure this module two times and always shows:
"Error occurred: ErrorInvalidIdMalformed. Check logs."
What should I do? How can I show you logs?

**Comment by d3nnsk4** [comment]
You enter the wrong id for your list.

-Go to [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer#)
-enter this url: https://graph.microsoft.com/beta/me/outlook/taskFolders/?$top=200
You dont need a body 
-> check out if you set Graph to beta and not v1.0
- Run the Query

You get a JSON Object with all your Lists and the right id which you can write into the config.

**Comment by KeramxD** [comment]
Thanks fo reply! :)
I did it and now see:

> Error occurred: ErrorItemNotFound. Check logs.

**Comment by d3nnsk4** [comment]
Looks like the item is deleted.
Create a new List with an item and try it again.

**Comment by thobach** [comment]
There seem to be some issues with the default "Tasks" list. Could you
please try to omit the "listId" parameter from the config file and see if
it shows the todos from the "Tasks" list? Does it work for other custom
lists than "Tasks"?

**Comment by ausheikh** [comment]
I have the same issue.
if i omit the listId parameter it works
but if i try another list it doesnt work.
When I try Graph Explorere (as suggested above) i dont see any of the other lists I have created.
the list Id that i used was from the URL when i select the list
https://to-do.live.com/tasks/**l-1xg1z0dy6e0**

**Comment by ausheikh** [comment]
> Thanks fo reply! :)
> I did it and now see:
> 
> > Error occurred: ErrorItemNotFound. Check logs.
> 
> This is my output:
> `{ "@odata.context": "https://graph.microsoft.com/beta/$metadata#users('48d31887-5fad-4d73-a9f5-3c356e68a038')/outlook/taskFolders", "value": [ { "id": "AAMkAGVmMDEzMTM4LTZmYWUtNDdkNC1hMDZiLTU1OGY5OTZhYmY4OAAuAAAAAAAiQ8W967B7TKBjgx9rVEURAQAiIsqMbYjsT5e-T7KzowPTAAAAAAESAAA=", "changeKey": "IiLKjG2I7E+Xv0+ys6MD0wACobVqbA==", "name": "Tasks", "isDefaultFolder": true, "parentGroupKey": "0006f0b7-0000-0000-c000-000000000046" } ] }`
> 
> so I pasted this to ID in config.js:
> `AAMkAGVmMDEzMTM4LTZmYWUtNDdkNC1hMDZiLTU1OGY5OTZhYmY4OAAuAAAAAAAiQ8W967B7TKBjgx9rVEURAQAiIsqMbYjsT5e-T7KzowPTAAAAAAESAAA=`



> Thanks fo reply! :)
> I did it and now see:
> 
> > Error occurred: ErrorItemNotFound. Check logs.
> 
> This is my output:
> `{ "@odata.context": "https://graph.microsoft.com/beta/$metadata#users('48d31887-5fad-4d73-a9f5-3c356e68a038')/outlook/taskFolders", "value": [ { "id": "AAMkAGVmMDEzMTM4LTZmYWUtNDdkNC1hMDZiLTU1OGY5OTZhYmY4OAAuAAAAAAAiQ8W967B7TKBjgx9rVEURAQAiIsqMbYjsT5e-T7KzowPTAAAAAAESAAA=", "changeKey": "IiLKjG2I7E+Xv0+ys6MD0wACobVqbA==", "name": "Tasks", "isDefaultFolder": true, "parentGroupKey": "0006f0b7-0000-0000-c000-000000000046" } ] }`
> 
> so I pasted this to ID in config.js:
> `AAMkAGVmMDEzMTM4LTZmYWUtNDdkNC1hMDZiLTU1OGY5OTZhYmY4OAAuAAAAAAAiQ8W967B7TKBjgx9rVEURAQAiIsqMbYjsT5e-T7KzowPTAAAAAAESAAA=`

Make sure you login (on the left, not the sign in top right) to Microsoft Graph Explorer, once i did that I got all the lists i created.

**Comment by thobach** [comment]
Please see also https://github.com/thobach/MMM-MicrosoftToDo/issues/11#issuecomment-593213539 which mentions that the short IDs generated from tasks through the Web UI don't seem to work. If you try to create a list through the mobile app, the task list ID should be a long one and work.

I adjusted the configuration now, to specify the task list name instead of the ID to simplify the process.
