### ISSUE TITLE
Offset in due date

### ISSUE THREAD

**Issue by mojomuffins** [thobach/MMM-MicrosoftToDo#24]
Hi there,

unfortunately all due dates are listed with an offset of 1day.
For instance an entry is due on july 4th, it is shown as due on july 3rd.

Thanks for your help!

**Comment by thobach** [comment]
Hi Jan, Could it be that you are using a fork of this module? This original
module does not display due dates, it only sorts entries by due date.

**Comment by mojomuffins** [comment]
Ahhh.... certainly, you are right, sorry! I'm having this issue with the solution described here: https://github.com/thobach/MMM-MicrosoftToDo/issues/14
