### ISSUE TITLE
Problem in Terminal

### ISSUE THREAD

**Issue by almero69** [thobach/MMM-MicrosoftToDo#25]
Hi,
**Can someone please check out what I am doing wrong. Have I missed something?
I only get error message. I have paste in Client ID, Code and Secret code.**

curl -X POST https://login.microsoftonline.com/common/oauth2/v2.0/token -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=authorization_code&client_id=**My client id**&scope=offline_access%20user.read%20tasks.read&code=**My code**&redirect_uri=https%3A%2F%2Flocalhost%3A1234&client_secret=**My secret cod**=ytP.["

**Comment by thobach** [comment]
Hi,

Could you please also remove the "=ytP.[" part at the end? It seems you
only replaced part of the client secret sample from the README with your
client secret.

Here is a template of the call without sample values but placeholders:
curl -X POST https://login.microsoftonline.com/common/oauth2/v2.0/token -H
"Content-Type: application/x-www-form-urlencoded" -d
"grant_type=authorization_code&client_id=YOUR_CLIENT_ID&scope=offline_access%20user.read%20tasks.read&codeYOUR_CODE&redirect_uri=https%3A%2F%2Flocalhost%3A1234&client_secret=YOUR_CLIENT_SECRET"

If you still get an error, please post here also the error message.

**Comment by almero69** [comment]
Thanks for your help! @thobach
Now, I have passed my earlier problem :-)
When I thought that everything was ok, I got this message in MM: "**Error occured: ErrorItemNotFound. Check logs.**" What to do now? I have create a list/task in To Do and even tried with the trick from @d3nnsk4 (https://graph.microsoft.com/beta/me/outlook/taskFolders/?$top=200)

**Comment by almero69** [comment]
I made it work today :-)
Thanks for a great module!
