### ISSUE TITLE
Complete Tasks?

### ISSUE THREAD

**Issue by aixsyd** [thobach/MMM-MicrosoftToDo#26]
Is is possible to check off/complete tasks via this API?

**Comment by thobach** [comment]
Hi,
According to
https://docs.microsoft.com/en-us/graph/api/outlooktask-complete?view=graph-rest-beta
this is supported by the API. It is not implemented though and would
require also to request more permissions in step "Authorization Code
Generation (Code)" and "Refresh Token Generation (Refresh Token)". Neither
should be difficult to do though.
The Magic Mirror though is generally not designed for many interactions,
especially not mouse interactions, but rather to view information. Could
you please describe your use case? Why and how you would like to check off
tasks? Thanks!

**Comment by aixsyd** [comment]
So in theory, I'd have a small touchscreen connected to a Pi, and I plan to
use this in an indoor growing room to check off daily tasks as they're
completed. I'd like to set up the tasks from home, or via Mobile, but
complete them specifically in the grow room. The reason I wouldn't just do
it via mobile is that its very easy to forget, and I'm not the only one in
the grow room completing tasks.

**Comment by aixsyd** [comment]
In theory, I'd be using Magic Mirror as a simple Kiosk that would show tasks for the day as a list, and as I complete them, be able to tap on them to complete them as you would on a desktop.

**Comment by lavolp3** [comment]
Thanks for the link @thobach! For some reason I did not find it.
@aixsyd I'm working on this but will probably publish it under another name since the module is completely different.

**Comment by thobach** [comment]
@aixsyd @lavolp3 Added the requested feature which can be used if the config value `completeOnClick` is set to `true`.

Note: If you had installed this module already, you may need to do steps https://github.com/thobach/MMM-MicrosoftToDo#authorization-code-generation-code and https://github.com/thobach/MMM-MicrosoftToDo#refresh-token-generation-refresh-token again and use the new `oauth2RefreshToken` in the config as the app now needs also write permissions for the tasks.
