### ISSUE TITLE
AADSTS9002325: Proof Key for Code Exchange is required for cross-origin authorization code redemption.

### ISSUE THREAD

**Issue by aixsyd** [thobach/MMM-MicrosoftToDo#27]
![image](https://user-images.githubusercontent.com/23741057/82927850-9d7c7b80-9f81-11ea-8db3-9b45807a5c75.png)

This is what happens when I follow the step:

**Authorization Code Generation (Code)**
Create authorization code by opening the following URL in your browser (but replace the client_id with your value):

**Comment by thobach** [comment]
Hi @aixsyd,

I found another user with a similar problem on https://stackoverflow.com/a/61729276.

Could you please check if you registered the app as "Web" and not "SPA"/"Single-page application" as per step 5 under "Web App Registration (Client ID)" from https://github.com/thobach/MMM-MicrosoftToDo#web-app-registration-client-id?

<img width="1236" alt="Bildschirmfoto 2020-06-07 um 15 43 54" src="https://user-images.githubusercontent.com/274056/83970421-f0d1c080-a8d5-11ea-9920-b7e4e6f08bf9.png">

Thanks!

**Comment by thobach** [comment]
Closing as there has been no response for a while for the provided answer.
