### ISSUE TITLE
invalid_grant error: Caused by incorrect prep guide URLs?

### ISSUE THREAD

**Issue by edward-dunton** [thobach/MMM-MicrosoftToDo#30]
Following the prep guide left me with a invalid_grant error

Adding tasks.read to the permissions in the prep guide URLs seemed to fix this 

Seems odd that tasks.readwrite does not superseed tasks.read, however, I did also disable the checkboxes so maybe that caused it?

**Comment by thobach** [comment]
Thanks Edward for identifying the issue, reporting it and providing a fix at the same time!
