### ISSUE TITLE
Color and update speed

### ISSUE THREAD

**Issue by Beastlynoob** [thobach/MMM-MicrosoftToDo#32]
I was wondering if there was a way to add color to the header and text of the to-do list?

I was also wondering I i could make the to-do list update every few seconds instead of 1 minute?

**Comment by thobach** [comment]
You can customize the coloring by creating a file in the `css` folder named `custom.css` and add as content:
`.MMM-MicrosoftToDo .module-header {
  color: red;
}

.MMM-MicrosoftToDo .module-content {
  color: blue;
}` 
with your colors of choice. See https://www.w3schools.com/Colors/colors_hexadecimal.asp for more details on CSS colors.

I also made the refresh interval configurable, see the new configuration option `refreshSeconds` at https://github.com/thobach/MMM-MicrosoftToDo#installation.
