### ISSUE TITLE
Error while trying to get token 

### ISSUE THREAD

**Issue by aidanw34** [thobach/MMM-MicrosoftToDo#33]
Every time I put:

curl -X POST https://login.microsoftonline.com/common/oauth2/v2.0/token -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=authorization_code&client_id=My-client-id&scope=offline_access%20user.read%20tasks.readwrite%20tasks.read&code=My-code&redirect_uri=https%3A%2F%2Flocalhost%3A1234&client_secret=My-client-secret.["

I get this back:

{"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: 60c018fb-32af-45ed-94d1-921ff3b68600\r\nCorrelation ID: 512eafbc-bbd6-4892-aba7-464449ce8993\r\nTimestamp: 2020-07-03 10:55:12Z","error_codes":[7000215],"timestamp":"2020-07-03 10:55:12Z","trace_id":"60c018fb-32af-45ed-94d1-921ff3b68600","correlation_id":"512eafbc-bbd6-4892-aba7-464449ce8993","error_uri":"https://login.microsoftonline.com/error?code=7000215"}

I have tried it multiple times and have done a fresh client secret as well yet it still won't work, don't know what I'm doing wrong, Im very new to this so no doubt user error.

Any help would be greatly appreciated.

**Comment by thobach** [comment]
Please note that ".[" belongs to the sample secret and should be removed:
`curl -X POST https://login.microsoftonline.com/common/oauth2/v2.0/token -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=authorization_code&client_id=<your-client-id>&scope=offline_access%20user.read%20tasks.readwrite%20tasks.read&code=<your-code>&redirect_uri=https%3A%2F%2Flocalhost%3A1234&client_secret=<your-client-secret>"`

Did this solve your issue?
