### ISSUE TITLE
The parameter "listName" is not always working

### ISSUE THREAD

**Issue by R-Studio** [thobach/MMM-MicrosoftToDo#35]
Hi this MagicMirror module is really nice and working, but I have a little issue with the parameter "listName".

The most of my "Task-Lists" are not working. The following error occurs:
**Error occurred: "<Task-List>" task folder not found. Check..**
The smart lists also not working.

Do you have any idea why this happens?
_Thanks for any help or reply._

**Comment by thobach** [comment]
Could you please share your configuration for the module, but obfuscate the oauth2ClientSecret and oauth2RefreshToken parameters?

**Comment by R-Studio** [comment]
> Could you please share your configuration for the module, but obfuscate the oauth2ClientSecret and oauth2RefreshToken parameters?

Hi this is my configuration:
```
{
                    module: 'MMM-MicrosoftToDo',
                    position: 'bottom_left',    // This can be any of the regions. Best results in left or right regions.
                    header: 'To-Do', // This is optional
                    config: {
                      oauth2ClientSecret: 'xx',
                      oauth2RefreshToken: 'xx'
                      oauth2ClientId: 'xx',
                      listName: 'Important', // optional parameter: if not specified displays tasks from default "Tasks" list, if specified will look for a task list with the specified name (exact spelling)
                      //listId: 'AQMkADAwATNiZmYAZC1iODgANS1hNGMyLTAwAi0wMAoALgAAA1Lh_i4gMGJMlZDpJ2d8iWwBAB_qpxIEaN5AgOOJ-T1mRJ8AAzJQqfYAAAA=', // deprecated parameter: use listName instead
                      showCheckbox: true, // optional parameter: default value is true and will show a checkbox before each todo list item
                      showDueDate: true, // optional parameter: default value is false and will show the todo list items due date if it exists on the todo list item
                      dateFormat: 'dd Do MMM [ - ]', //optional parameter: uses moment date format and the default value is 'ddd MMM Do [ - ]'
                      hideIfEmpty: false, // optional parameter: default value is false and will show the module also when the todo list is empty
                      maxWidth: 450, // optional parameter: max width in pixel, default value is 450
                      itemLimit: 30, // optional parameter: limit on the number of items to show from the list, default value is 200
                      //orderBy: 'subject', // optional parameter: 'subject' - order results by subject/name, 'dueDate' - order results by due date, default value is unordered
                      completeOnClick: true, // optional parameter: default value is false, when set to true complete task when clicking on it
                    }
},
```

if I create a new Task-List then everything works, but if I use a the Smartlist "Important" or my own old Task-List "Idea / Long Running Tasks" then the error occurs.

**Comment by R-Studio** [comment]
Do you have any idea whats wrong?

**Comment by R-Studio** [comment]
I think I found the issue.
![image](https://user-images.githubusercontent.com/7498854/91047926-25befb00-e61b-11ea-9a77-5aea276a82a7.png)


Here you can see the "importance" is only an flag on each task and not a TaskList (Taskfolder):
![image](https://user-images.githubusercontent.com/7498854/91047827-f9a37a00-e61a-11ea-8089-999115270b4b.png)


_Because of this, I think my github issue is a feature request not a bug._

**Comment by thobach** [comment]
I agree and thanks for your pull request #40. Once the open issues are resolved, I can merge it, thanks!
