### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by runninbutt** [thobach/MMM-MicrosoftToDo#36]
Please add screenshots of the module to help people considering the module.

**Comment by thobach** [comment]
My pleasure @runninbutt, I uploaded it to https://raw.githubusercontent.com/thobach/MMM-MicrosoftToDo/master/screenshots/microsoft%20todo%20magic%20mirror%20module.png and displayed them on https://github.com/thobach/MMM-MicrosoftToDo/blob/master/README.MD.
