### ISSUE TITLE
Wrong due date shown

### ISSUE THREAD

**Issue by sglock** [thobach/MMM-MicrosoftToDo#39]
Hi, 
first off all thank you for this module. Running the mirror on a Rasperry Pi 3. Istallled the module moths ago and up until now no problems. 
Switched to the parameter "listName" and included a task list with due dates. The list is shown but the due dates are wrong. In ToDo the due date is set to the 24.08.2020 but the mirror shows the task due on the 23.08.2020. This happens with all tasks. I am located in Germany and already checked if there is a time zone issue with the microsoft account but the dates match and time zone is set to (UTC+01:00) Amsterdam, Berlin, Bern, Rom, Stockholm, Wien. 
Maybe someone else is experiencing the same issue or can help!

`config: {
oauth2ClientSecret: 'XXXXXXXXXXXXXX',
oauth2RefreshToken: 'XXXXXXXXXXXXXX',
oauth2ClientId: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
listName: 'Essensplan',
showCheckbox: true,
showDueDate: true, 
dateFormat: 'ddd MMM Do [ - ]',
hideIfEmpty: false,
maxWidth: 450,
itemLimit: 200,
orderBy: 'dueDate',
}`

**Comment by korovascope** [comment]
Hi,

Just a +1 on this issue, as I'm experiencing the same thing.  Local timezone is GMT+10, and system timezone & time/date is set correctly.

Cheers!

**Comment by korovascope** [comment]
Looking into it, the date is coming from ToDo as UTC, but is not being specifically converted into the local timezone.

Changing line 30 in MMM-MicrosoftToDo.js  to:
`		  taskDue = moment.utc(taskDue[0]).tz("YOUR TIMEZONE HERE").format(self.config.dateFormat)`

seems to bring everything back to the correct date.

**Comment by sglock** [comment]
Hi korovascope,
thx for the solution. Just tried your solution and solved the problem. 
@thobach Might be usefull to incorporate the change in the repo

**Comment by thobach** [comment]
Sorry for not testing this feature properly in the first place. It fixed now.
