### ISSUE TITLE
Depreciated parameter: listId - needs to be changed to listName

### ISSUE THREAD

**Issue by magic21nrw** [thobach/MMM-MicrosoftToDo#41]
I get the following output in the Log-File. It seems that the Command for the API is depreciated and should be changed.

 [2020-09-09 19:27:15.379] [WARN]   MMM-MicrosoftToDo - Warning, configuration parameter listId is deprecated, please use listName instead, otherwise the module will not work anymore in the future.

There should be a change from listId to listName.

**Comment by thobach** [comment]
@magic21nrw I'm actually deprecating listId and not listName, see https://github.com/thobach/MMM-MicrosoftToDo#installation. listId is in some cases hard to extract, hence I'm using by default now listName which is more human friendly.
