### ISSUE TITLE
Stuck on Authorization Code Generation

### ISSUE THREAD

**Issue by BaggyJeans** [thobach/MMM-MicrosoftToDo#43]
After adjusting the link ...
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=4ef19f40-4892-4905-b999-76041e991f53&scope=offline_access%20user.read%20tasks.readwrite%20tasks.read&redirect_uri=https://localhost:1234&response_mode=query&state=12345 
... to include my client ID and hitting enter I end up getting the following message:

This site can’t be reached 
localhost refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

Do you have any thought on what might be blocking?

I have double checked the redirect URI. It is correct.

**Comment by thobach** [comment]
Hi @BaggyJeans,
This is expected. We're only interested in the URL parameters, in particular the `code` parameter, please see https://github.com/thobach/MMM-MicrosoftToDo#authorization-code-generation-code.

**Comment by BaggyJeans** [comment]
Hi thobach,

the URL I end up with looks nothing like the example you show in the guide:
https://localhost:1234/?error=invalid_request&error_description=The%20request%20is%20not%20valid%20for%20the%20application%27s%20%27userAudience%27%20configuration.%20In%20order%20to%20use%20/common/%20endpoint%2c%20the%20application%20must%20not%20be%20configured%20with%20%27Consumer%27%20as%20the%20user%20audience.%20The%20userAudience%20should%20be%20configured%20with%20%27All%27%20to%20use%20/common/%20endpoint.&state=12345

and the word code is nowhere in there.

**Comment by BaggyJeans** [comment]
By looking at the link I now understand where I went wrong.

**Comment by pastormingle** [comment]
I am getting the same issue. What did you do to fix it?

**Comment by BaggyJeans** [comment]
Hi, you chose the wrong selection somewhere in the third step. When you take out all the extra symbols in the URL it will say tell you what setting it was. Specifically in my case the user audience was wrong, apparently i chose consumer only.

Select as "Supported account types": "Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)"

You probably selected just one of the two, when you should have selected both.


________________________________
Van: pastormingle <notifications@github.com>
Verzonden: maandag 2 november 2020 21:53
Aan: thobach/MMM-MicrosoftToDo <MMM-MicrosoftToDo@noreply.github.com>
CC: BaggyJeans <mark_spithoff@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [thobach/MMM-MicrosoftToDo] Stuck on Authorization Code Generation (#43)


I am getting the same issue. What did you do to fix it?

**Comment by pastormingle** [comment]
Thanks for following up BaggyJeans.. I am still not able to get a code even after trying IE instead of chrome. This is the link i am using and putting my my ID "MY ID CODE"  "https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=MY ID CODE&scope=offline_access%20user.read%20tasks.
Is this correct?

**Comment by thobach** [comment]
@pastormingle I think your URL is missing the following at the end "readwrite%20tasks.read&redirect_uri=https://localhost:1234&response_mode=query&state=12345".

Please watch out that the code blocks in the readme file are quite long and not everything may be shown on the screen without horizontal scrolling.
If you triple click on the URL on the readme file it should select the entire line which you can copy and past to e.g. a text editor to adjust and then copy and past into your terminal.

**Comment by Ntracks** [comment]
Does not work for me as well - i have added "Value" and "ID" instead of >>MY_ID_CODE<< but there is only an error message.

> https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=>>MY_ID_CODE<<&scope=offline_access%20user.read%20tasks.readwrite%20tasks.read&redirect_uri=https://localhost:1234&response_mode=query&state=12345

I only get:

> unauthorized_client: The client does not exist or is not enabled for consumers. If you are the application developer, configure a new application through the App Registrations in the Azure Portal at https://go.microsoft.com/fwlink/?linkid=2083908.

**Comment by thobach** [comment]
Hi @Ntracks, The "Value" (client secret) is only needed in again in step "Refresh Token Generation (Refresh Token)" (https://github.com/thobach/MMM-MicrosoftToDo#refresh-token-generation-refresh-token). In step "Authorization Code Generation (Code)" (https://github.com/thobach/MMM-MicrosoftToDo#authorization-code-generation-code) you will needed the "Application (client) ID" (Client ID) from step "Web App Registration (Client ID)" (https://github.com/thobach/MMM-MicrosoftToDo#web-app-registration-client-id).
If you send me to info@thobach.de some screenshots of your Azure portal app setup and the URLs you generated, I may be able to help you trouble shoot further, e.g. confirm that the URL with the client ID is correct, the app is correctly configured to be enabled for consumers, etc.

**Comment by Ntracks** [comment]
Okay der Schritt wäre jetzt geschafft. War etwas verwirrend :D
So jetzt hänge ich aber beim nächsten Schritt - ich habe die ID den Code usw. in den Terminal befehl kopiert und bekomme einen error...

>{"error":"unauthorized_client","error_description":"AADSTS700016:
usw.

Ich würd das dermaßen feiern, wenn du dazu ne YouTube Anleitung machen könntest.
Würd dir auf jeden Fall ein Like und ein Abo dalassen!

**Comment by thobach** [comment]
I just checked the procedure with a fresh Microsoft account and it still works for me. Note: This setup does not work under an Azure Germany (with T-Systems as data trustee) account.

To rule out that there is any issue with your Microsoft account, please try it with a fresh one by going to https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredApps, select "Create one!" and follow the Microsoft account creation process.

Afterwards please see my video with recorded instructions for the creation of the Azure Client ID, secret and refresh token: https://www.youtube.com/watch?v=3JPkm3bVR4w

Please let me know if you still face any difficulties, thanks!

**Comment by robertybob** [comment]
This isn't working for me either. I've double-checked that I've followed the steps in the readme , yet I still get 
![image](https://user-images.githubusercontent.com/2610395/120938763-774cf800-c70c-11eb-8ff2-8fb6a8a5df51.png)

**Comment by thobach** [comment]
Hi @robertybob,
This is expected. We're only interested in the URL parameters, in particular the code parameter, please see https://github.com/thobach/MMM-MicrosoftToDo#authorization-code-generation-code.
