### ISSUE TITLE
You can't sign in here with a personal account. Use your work or school account instead.

### ISSUE THREAD

**Issue by accountnumber3** [thobach/MMM-MicrosoftToDo#46]
Trying to do the [code generation](https://github.com/thobach/MMM-MicrosoftToDo#authorization-code-generation-code) and it's giving me this error. Does it require a subscription or something? Is there an alternative?

**Comment by thobach** [comment]
Hi @accountnumber3, Could you please try it with a newly created Microsoft account? It does not require a subscription.

**Comment by dirk-graetz** [comment]
Hi,
i have the same problem while getting Authorization Code - you can't sign in here with a personal account.

**Comment by thobach** [comment]
I just checked the procedure with a fresh Microsoft account and it still works for me. Note: This setup does not work under an Azure Germany (with T-Systems as data trustee) account.

To rule out that there is any issue with your Microsoft account, please try it with a fresh one by going to https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredApps, select "Create one!" and follow the Microsoft account creation process.

Afterwards please see my video with recorded instructions for the creation of the Azure Client ID, secret and refresh token: https://www.youtube.com/watch?v=3JPkm3bVR4w

Please let me know if you still face any difficulties, thanks!

**Comment by BigChaps** [comment]
Can confirm that it works with a Microsoft Consumer account, the bit that threw me was that the Secret uses the Value, Of course, when I re-read the instructions, it was specifically mentioned <facepalm>
