### ISSUE TITLE
invalid grant. check logs

### ISSUE THREAD

**Issue by gkchim** [thobach/MMM-MicrosoftToDo#47]
Hi,
I am getting the below:

Error occurred: invalid_grant. Check logs.

Tried re-doing incase i missed anything, but no luck - how can i check logs please?

**Comment by SokolovskiR** [comment]
I have the same problem which occurred couple of days ago. Could it be an issue with a German Azure account? 
![grafik](https://user-images.githubusercontent.com/59457122/104637390-05184000-56a5-11eb-8a6e-1066568f5c1a.png)

**Comment by fzimmerli** [comment]
I experienced the same and get the same result as gkchim.

**Comment by thobach** [comment]
I just checked the procedure with a fresh Microsoft account and it still works for me. Note: This setup does not work under an Azure Germany (with T-Systems as data trustee) account.

To rule out that there is any issue with your Microsoft account, please try it with a fresh one by going to https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredApps, select "Create one!" and follow the Microsoft account creation process.

Afterwards please see my video with recorded instructions for the creation of the Azure Client ID, secret and refresh token: https://www.youtube.com/watch?v=3JPkm3bVR4w

Please let me know if you still face any difficulties, thanks!

**Comment by SokolovskiR** [comment]
@thobach thanks for your tutorial, Thomas, just worked perfectly for me!

**Comment by hildwin** [comment]
I experienced the same. Worked for me with a new registration with the same account.

**Comment by ChrizZz90** [comment]
I have the same error now and I see that this appears exactly 1 year after using it the first time. This issue isn't related to the type of account it is, as mentioned in the error logs, based on the API data which is expired.

**Comment by magic21nrw** [comment]
Just a little comment: Be careful not to copy the whole answer when copying the response key which includes two keys in the last step. This happened with me and made me wonder why it is not working. So only copy the second half of the response.

The key refresh worked for me, too. Unfortunately Microsoft does not allow unlimited certificates anymore. The maximum you can go is 2 years.
