### ISSUE TITLE
Device authorization grant viable improvement?

### ISSUE THREAD

**Issue by Teetime** [thobach/MMM-MicrosoftToDo#48]
Hello,

during setup I made a mistake in the azure configuration (by not reading correctly) which caused an error.
While googling for this error I stumbled upon [this site](https://docs.microsoft.com/en-US/azure/active-directory/develop/v2-oauth2-device-code) where Microsoft describes how to authorize devices with limited input options.

This way the user just has to visit the page https://microsoft.com/devicelogin and enter a code in the browser to grant the permissions without extracting any codes, IDs and secrets from some URIs and build new ones with that.
On the client side it would need two new types of requests to be sent to the Microsoft server, instruct the user to visit the website and enter the code and then and wait until the user consented and save the refresh-token for later use.
I guess the user still has to create a new app because they still need a client id.

Not sure if this would works like I imagine because I know nothing about Azure and how your module works but if its possible I think installing would be way easier and comfortable than it is now.

**Comment by thobach** [comment]
Thanks for the suggestion. It would indeed only make the refresh-token retrieval easier for the user. Further the MMM-MicrosoftToDo module would need to store that token somewhere during the setup and then read it when launched. If you'd like to implement it, I'm happy to support you, if you send me a pull request ;)
