### ISSUE TITLE
Cant get Refresh token?

### ISSUE THREAD

**Issue by Johann-vln** [thobach/MMM-MicrosoftToDo#50]
HI i tried this but it didnt work:
curl -X POST https://login.microsoftonline.com/common/oauth2/v2.0/token -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=authorization_code&client_id=60cdab3f-1376-4b1f-9070-3f082284cff8&scope=offline_access%20user.read%20tasks.readwrite%20tasks.read&code=M30cd0dff-af91-d061-8755-ffb3b328aa03&redirect_uri=https%3A%2F%2Flocalhost%3A1234&client_secret=231da39b-cfc0-465e-8417-69c25f3f829b"

It gave me this error:

{"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: d599dd19-fdef-4a4c-a9fb-65fc6e230b00\r\nCorrelation ID: 3320ab88-ddfb-4b67-8d5b-3029ab8643a2\r\nTimestamp: 2021-03-03 09:31:29Z","error_codes":[7000215],"timestamp":"2021-03-03 09:31:29Z","trace_id":"d599dd19-fdef-4a4c-a9fb-65fc6e230b00","correlation_id":"3320ab88-ddfb-4b67-8d5b-3029ab8643a2","error_uri":"https://login.microsoftonline.com/error?code=7000215"}pi@raspberrypi:~ $ M.R3_BAY.33e97601-d42e-1ef5-5ab8-f7a31d3a699e

What did i do wrong?

**Comment by thobach** [comment]
Hi @Johann-vln, The format of your client secret indicates that you did not use the right value here. Please see https://github.com/thobach/MMM-MicrosoftToDo#client-secret-key-generation-client-secret for details how to generate the client secret or please see my video with recorded instructions for the creation of the Azure Client ID, secret and refresh token: https://www.youtube.com/watch?v=3JPkm3bVR4w

Please let me know if you still face any difficulties, thanks!
