### ISSUE TITLE
due date support for repeated tasks

### ISSUE THREAD

**Issue by zangzhw** [thobach/MMM-MicrosoftToDo#51]
When marked as done, the repeated task will be marked undone and have the due date updated.
As a result, the repeated tasks will always be on the list, but without any further information.
So I am wondering if the due date can be displayed for the repeated tasks so that I can know whether the repeated tasks were finished in this wave.

**Comment by thobach** [comment]
#52 added icon to recurring items, does this and some other fixes done in the meantime address the issue?
