### ISSUE TITLE
more than 1 tasklist

### ISSUE THREAD

**Issue by chethanbr86** [thobach/MMM-MicrosoftToDo#53]
Is there a possibility to add more than one task list?
I tried but it did not work.
I don't know javascript to make changes in the code.

I just tried to add another list like below:
listName = ['taks1', 'task2'],   (also without parenthesis but did not work).

**Comment by thobach** [comment]
Hi @chethanbr86, 
You can add the module multiple times to the modules array in the config file.
Would this be sufficient or do you need to merge two lists in one module? In which case why not have just one list in the first place?

**Comment by chethanbr86** [comment]
I was thinking, if there were more lists in the same module, we can cycle between the lists for a particular time period. 
The problem with multiple modules is multiple spaces will be taken up on the monitor which doesn't allow other modules. 
And the problem with a single list will be a long list with the same spacing problem.

**Comment by thobach** [comment]
For this case I suggest to try out modules like https://github.com/barnabycolby/MMM-Carousel with its 'positional' mode. It should allow you to rotate multiple instances of a module in the same position.

**Comment by chethanbr86** [comment]
Thank you
