### ISSUE TITLE
Visual formatting of display fields

### ISSUE THREAD

**Issue by edgard** [thobach/MMM-MicrosoftToDo#59]
Is there a way to visually format the fields displayed? I'm trying to make it look like the calendar module, just for the sake of consistency but I can't find how.

Currently it's like this: https://i.imgur.com/vlFNlCo.jpg

I would like to format the dates like the calendar one on the bottom. Justified to the right, etc.

**Comment by thobach** [comment]
Due date is now prepended, if that helps. Feel free to send a merge request with the option to show the due date right aligned.
