### ISSUE TITLE
[Bug] possibly css bug?

### ISSUE THREAD

**Issue by TimerWolf** [thobach/MMM-MicrosoftToDo#6]
Sorry for the bad view, but as you see it does mess up the other modules when it are in the "top_right" whit them.

I don´t know if it is how it actually works, or if it is a bug but i think it was worth to show

![Image](https://i.imgur.com/8RMSH87.png)

**Comment by thobach** [comment]
Fixed, I added configurable maximum width with the default being 450px. You can add the config parameter `maxWidth` and set it to e.g. `350` to limit its width to 350px.
