### ISSUE TITLE
Mirror not loading

### ISSUE THREAD

**Issue by gvlewis** [thobach/MMM-MicrosoftToDo#60]
hello,

i'm very basic user and trying to set this up for my display. I've followed everything in the instructions and am sure the code etc is all correct. However once i have placed the module info into the config file the mirror fails to load and stays on a black screen. It is relating to TO DO module as once i remove the module its fine again.

Appreciate any help for a newby!

**Comment by gvlewis** [comment]
i've managed to resolve this. had to run npm install in the todo module and magic mirror folders which seemed to fix it

**Comment by getchethanbr** [comment]
> i've managed to resolve this. had to run npm install in the todo module and magic mirror folders which seemed to fix it

I tried this but still I am getting black screen.

**Comment by spyder007** [comment]
What version of MagicMirror are you running?  Check the discussion on #64 , if you're running the updated Magic Mirror, you'll need to install the `request` module for this library until PR #66 is merged.

**Comment by thobach** [comment]
#66 was merged
