### ISSUE TITLE
Codes and Ids are correct but it won't appear on my mirror. Doesnt crash or say corrupt 

### ISSUE THREAD

**Issue by NickD135** [thobach/MMM-MicrosoftToDo#61]
Codes and Ids are correct but it won't appear on my mirror. Doesn't crash or say corrupt. It just doesn't appear. I am wondering if I have to somehow sync my Microsoft to do or if it will just do it automatically.

**Comment by thobach** [comment]
@NickD135 Do you get some error messages in the magic mirror logs or the browser logs?

**Comment by thobach** [comment]
I improved error logging in last commit https://github.com/thobach/MMM-MicrosoftToDo/commit/9e9ba1a6e5edde5a6be782b5e633a8285b3769f8. Could you please update to the latest version with `git pull` and post the related logs from Magic Mirror? Thanks!
