### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by DLBorup** [thobach/MMM-MicrosoftToDo#68]
After todays update i just get a black screen whenever the module is activated. 

When running PM2 i get the following error: 

.pm2/logs/mm-error.log last 15 lines:
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Microso ftToDo/node_helper.js:11:50)
0|mm       |     at Module._compile (node:internal/modules/cjs/loader:1116:14)
0|mm       |     at Object.Module._extensions..js (node:internal/modules/cjs/loa der:1169:10) {
0|mm       |   code: 'MODULE_NOT_FOUND',
0|mm       |   requireStack: [
0|mm       |     '/home/pi/MagicMirror/modules/MMM-MicrosoftToDo/node_helper.js' ,
0|mm       |     '/home/pi/MagicMirror/js/app.js',
0|mm       |     '/home/pi/MagicMirror/js/electron.js',
0|mm       |     '/home/pi/MagicMirror/node_modules/electron/dist/resources/defa ult_app.asar/main.js',
0|mm       |     undefined
0|mm       |   ]
0|mm       | }
0|mm       | [03.01.2022 20:07.16.969] [ERROR] MagicMirror will not quit, but it  might be a good idea to check why this happened. Maybe no internet connection?
0|mm       | [03.01.2022 20:07.16.970] [ERROR] If you think this really is an is sue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/iss ues
0|mm       | /home/pi/MagicMirror/node_modules/electron/dist/electron exited with signal SIGINT

Had a similar issue when first installing the module, but it was fixed with "npm install request --save + Restart MM" But that does not seem to work this time around. 

i tried removing the folder and make a fresh clone, but that did not change anything. I have changed nothing in config.js and had no changes within the MMM-MicrosoftToDo folder.

**Comment by thobach** [comment]
Sorry for the trouble, this module requires now to run `npm install`, which will install `date-fns`.
See new step 2 at https://github.com/thobach/MMM-MicrosoftToDo#installation.

**Comment by DLBorup** [comment]
Thank you for the quick answer (and sorry for not catching the new Step 2) that seemed to fix it. 

And thank you for a cool module.

**Comment by DLBorup** [comment]
Thank you for the quick reply (and sorry for not catching the new step 2) that seemed to fix it. And thank you for an amazing module. :)
