### ISSUE TITLE
localhost

### ISSUE THREAD

**Issue by seby2** [thobach/MMM-MicrosoftToDo#7]
hi, I don't understand what am I suppose to enter as a localhost....
tks for your help
Seby

**Comment by seby2** [comment]
Please help anyone. I don't understand if I really have to put 12345 in there.
tks
Seby

**Comment by seby2** [comment]
in the 5th step
Set as "Redirect URI": "https://localhost:1234"
what I put as 1234?
tks
Seby

**Comment by thobach** [comment]
You can leave the value as is: "https://localhost:1234". Microsoft will redirect you in your browser to this URL. You will need to copy the code parameter from the redirected URL.

**Comment by seby2** [comment]
> You can leave the value as is: "https://localhost:1234". Microsoft will redirect you in your browser to this URL. You will need to copy the code parameter from the redirected URL.

Tks for the reply. I really did every step you have wrote. But still no luck. No error, no nothin but no result. I must have missed something but can't figure it out.
Is there a way you could help me? Like screensharing or I don't know..
Tks
Seby

**Comment by thobach** [comment]
Hi Seby, Could you please provide some screenshots of your setup and the process where you retrieved the oauth2ClientSecret, oauth2RefreshToken, oauth2ClientId and listId from? Maybe we can help you then.

**Comment by thobach** [comment]
Closing the issue since there was no further response.
