### ISSUE TITLE
completeOnClick error

### ISSUE THREAD

**Issue by PiranhaBgl** [thobach/MMM-MicrosoftToDo#71]
Hi,
I have 2 error when i try to complete a task (with a touchscreen) with the last version of all magicmirror and of MMM-Microsofttodo
pm2 logs:
0|MagicMirror  | [07.01.2022 20:42.13.209] [ERROR]
0|MagicMirror  | Whoops! There was an uncaught exception...
0|MagicMirror  | [07.01.2022 20:42.13.214] [ERROR] TypeError: fetch(...).then(...).then(...).then(...).then(...).error is not a function
0|MagicMirror  |     at Class.completeTask (/home/pi/MagicMirror/modules/MMM-MicrosoftToDo/node_helper.js:55:8)
0|MagicMirror  |     at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-MicrosoftToDo/node_helper.js:21:12)
0|MagicMirror  |     at Socket.<anonymous> (/home/pi/MagicMirror/js/node_helper.js:109:11)
0|MagicMirror  |     at Socket.emit (node:events:394:28)
0|MagicMirror  |     at Socket.emitUntyped (/home/pi/MagicMirror/node_modules/socket.io/dist/typed-events.js:69:22)
0|MagicMirror  |     at /home/pi/MagicMirror/node_modules/socket.io/dist/socket.js:466:39
0|MagicMirror  |     at processTicksAndRejections (node:internal/process/task_queues:78:11)
0|MagicMirror  | [07.01.2022 20:42.13.218] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|MagicMirror  | [07.01.2022 20:42.13.221] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|MagicMirror  | [07.01.2022 20:42.13.447] [ERROR]
0|MagicMirror  | (node:1731) UnhandledPromiseRejectionWarning: Error: Unauthorized
0|MagicMirror  |     at checkFetchStatus (/home/pi/MagicMirror/modules/MMM-MicrosoftToDo/node_helper.js:259:13)
0|MagicMirror  |     at runMicrotasks (<anonymous>)
0|MagicMirror  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|MagicMirror  | [07.01.2022 20:42.13.450] [ERROR] (node:1731) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)

Could you help me?

**Comment by spyder007** [comment]
There were some issues with the token not surviving as well as an oversight on my end.  I believe I have fixed this, but as I don't have touch available, can you please verify with
https://github.com/spyder007/MMM-MicrosoftToDo/tree/feature/complete-error

before I do a full PR?

**Comment by PiranhaBgl** [comment]
Hello Spyder007, with your https://github.com/spyder007/MMM-MicrosoftToDo/tree/feature/complete-error
i have exactly the same error :(

**Comment by thobach** [comment]
Could fixed an error with task completion in last commit https://github.com/thobach/MMM-MicrosoftToDo/commit/9e9ba1a6e5edde5a6be782b5e633a8285b3769f8. Could you please update to the latest version with `git pull` and confirm it works again, or post the related logs from Magic Mirror? Thanks!

**Comment by PiranhaBgl** [comment]
Hello,
it's done yesterday: it's wonderfull, it's works now

Thanks a lot
