### ISSUE TITLE
ERROR: Bad Request with plannedTasks true

### ISSUE THREAD

**Issue by jjonnela** [thobach/MMM-MicrosoftToDo#75]
I have a fresh install of MagicMirror and this module but I receive this error. The task retrieving works when using listName but not when using plannedTasks. (Same thing on PC and Raspberry PI)

![Here's screenshot](https://i.imgur.com/yv6rwXg.png)

It looks like it successfully finds the lists but has some kind of problem actually fetching them.

Here's my config (There's no regex on includedLists so it's trying to fetch all lists but the same error occurs with only 1 list) :

	  {
 	   module: 'MMM-MicrosoftToDo',
  	   position: 'top_left',	// This can be any of the regions. Best results in left or right regions.
	   header: 'ToDoList', // This is optional
 	   config: {
  	   	oauth2ClientSecret: 'xxxx',
   	   	oauth2RefreshToken: 'xxxx',
   	   	oauth2ClientId: 'xxxx',
   	 plannedTasks: {
   	   enable: true,
  	    includedLists: [""],
  	    duration: {
  	      weeks: 4
 	     }
 	   },
 	   }
 	 }

**Comment by thobach** [comment]
I improved error logging in last commit https://github.com/thobach/MMM-MicrosoftToDo/commit/9e9ba1a6e5edde5a6be782b5e633a8285b3769f8. Could you please update to the latest version with `git pull` and post the related logs from Magic Mirror? Thanks!

**Comment by spyder007** [comment]
@jjonnela you have to have at least one valid value in the `includedLists` value.  That array takes any regex, and the default is setup to match all lists.  I'd you want all lists, just remove that value in your config and let the default take over.

**Comment by jjonnela** [comment]
@thobach Here's the error

[24.01.2022 16:40.38.357] [ERROR] Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: Gunzip {
      _writeState: [Uint32Array],
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      bytesWritten: 0,
      _handle: [Zlib],
      _outBuffer: <Buffer 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... 16334 more bytes>,
      _outOffset: 0,
      _chunkSize: 16384,
      _defaultFlushFlag: 2,
      _finishFlushFlag: 2,
      _defaultFullFlushFlag: 3,
      _info: undefined,
      _maxOutputLength: 1073741823,
      _level: -1,
      _strategy: 0,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: null,
      [Symbol(kError)]: null
    },
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'https://graph.microsoft.com/v1.0/me/todo/lists/xxxxx/tasks?$top=200&$filter=status%20ne%20%27completed%27%20and%20duedatetime%2Fdatetime%20lt%20%272022-02-21T16%3A40%3A37%2B02%3A00%27%20and%20duedatetime%2Fdatetime%20ne%20null&$orderby=duedatetime/datetime',
    status: 400,
    statusText: 'Bad Request',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 0
  }
}
[24.01.2022 16:40.38.364] [ERROR] [MMM-MicrosoftToDo]: Error: checkFetchStatus failed with status 'Bad Request' {"size":0,"t

**Comment by thobach** [comment]
@jjonnela I assume your timezone is not in the Greenwich Mean Time / Western European Time zone. I had the same issue being based in UTC+1 and addressed the issue by adjusting the filter query to remove the timezone. Please check out the latest version.
@spyder007 FYI

**Comment by spyder007** [comment]
Thanks @thobach, I have been thinking about how to add a few tests to this to check for these things.  For sidetracked with my day job!  Thanks for the assist.
