### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by cruzher** [thobach/MMM-MicrosoftToDo#79]
Hi,

Magic mirror cannot fetch the lists. I've tried to search for a solution for this but I cannot find anything useful.

Magic mirror output gives me the following error:
>[10.03.2022 14:16.09.337] [ERROR] [MMM-MicrosoftToDo]: fetchList https://graph.microsoft.com/v1.0/me/todo/lists/?$top=200
>[10.03.2022 14:16.09.340] [ERROR] [MMM-MicrosoftToDo]: TypeError: Cannot read properties of undefined (reading 'findIndex')

I've tried to follow the instructions to create secrets and ID's again, seems to be correct.

My config looks like this:

```
{
    	module: 'MMM-MicrosoftToDo',
    	position: 'bottom_left',	// This can be any of the regions. Best results in left or right regions.
    	header: 'Planerat', // This is optional
    	config: {
      		oauth2ClientSecret: '...',
      		oauth2RefreshToken: '...',
      		oauth2ClientId: '...',
      		// Optional parameter:  see Planned Tasks Configuration
      		plannedTasks: {
        		enable: true,
      		}
    	}
  },
```

Any help would be much appreciated

**Comment by thobach** [comment]
Hi @cruzher, If you set `plannedTasks: {
        		enable: true,
      		}` you'll also need to set the other parameters for the task planning as per: https://github.com/thobach/MMM-MicrosoftToDo#planned-tasks-configuration

**Comment by cruzher** [comment]
Hi,

Thank you, it worked when I entered duration and includedLists. However I did follow this instruction as the default values were fine for me to start with.

> In other words, if you just enable the Planned Tasks configuration, the default values for duration and includedLists will take tasks from all lists which are not completed and have a due date less than 2 weeks from today. That will include any tasks that are overdue.

If these settings are required, these arent really default values, right?

Thanks again, Regards.

**Comment by thobach** [comment]
Thanks @cruzher, I fixed the issue with the default values now.
