### ISSUE TITLE
[Bug] Checkbox

### ISSUE THREAD

**Issue by TimerWolf** [thobach/MMM-MicrosoftToDo#8]
Not on me to report (as i don´t use it) but, i can see the checkbox on the mirror but if i "tick" it or mark it as "completed" or whatever word it for it it "in the phone application" as an example it still show as unmarked or disappear i don´t remember on the mirror.

My point whit this is that as the feature works today its 100% pointless....

**Comment by thobach** [comment]
The checkbox is only a visual cue that this is a todo list, without any function behind it. Since the Magic Mirror is generally just used for display purposes I don't intend to add this functionality, but I am happy if someone else wants to implement it.
