### ISSUE TITLE
Font Awesome icons not loading

### ISSUE THREAD

**Issue by cedrikl** [thobach/MMM-MicrosoftToDo#82]
So I updated both the magic mirror and this module and since then the icon for recurring tasks does not show properly.
![2022-04-27-192654_342x189_scrot](https://user-images.githubusercontent.com/24951043/165647418-7dfa8ed5-a730-4672-9601-657e52b25485.png)
I'm pretty sure it has something to do with the FA update to 6.0.
I tried modifying MMM-MicrosoftToDo.css and change the line
`recurringIcon.className = "fas fa-redo";`
to
`recurringIcon.className = "fa-solid fa-arrow-rotate-right";` to match [this](https://fontawesome.com/icons/arrow-rotate-right?s=solid)
without success sadly. I'm not a web dev at all so I have no clue how to debug this further.
Any help is appreciated.

Thanks,
CL

**Comment by thobach** [comment]
Thanks for the report. I could reproduce the display issue on Chrome and electron (not on Safari), and could not find out the cause either. I replaced the font awesome icon with an image in the end.

**Comment by cedrikl** [comment]
Can confirm it's fixed now. Thanks again :)

**Comment by spyder007** [comment]
For what it's worth, in the "recurring" icon (the fa-redo), the problem was that we were setting the font-weight.  Removing the font-weight from the style lets the image show correctly.
