### ISSUE TITLE
User not a member of tenant

### ISSUE THREAD

**Issue by mithrandir80** [thobach/MMM-MicrosoftToDo#83]
Since a couple of days I have an error loading my lists after months of working perfectly. Error message in MagicMirror was that user could not be authenticated due to account expiration. After login in Azure/Microsoftonline I see a message:
The logged in user is not authorised to fetch tokens for extension ‘Microsoft_AAD_IAM’ because user is not a member of tenant.

Any ideas or suggestions to solve this?

![F83605D2-5384-4B15-A365-27D8D467795B](https://user-images.githubusercontent.com/73595314/168673405-dd878e4d-216e-435f-b919-50bc54b17213.jpeg)

**Comment by Alex-lob** [comment]
Hello I have the same Error Message in my Azure Account. 

LG aus Deutschland

**Comment by thobach** [comment]
Thanks @mithrandir80 for the report. From https://github.com/thobach/MMM-MicrosoftToDo/issues/81#issuecomment-1140390812 I see that you could resolve the issue with:

> What worked for me was going through the azure process again. Following the steps in the tutorial from Client Secret Key Generation till the end. I deleted old secret key first but might work with two as well.

@Alex-lob Could you please try this as well? Or first check if the secret at this screen is not expired?
<img width="649" alt="Bildschirmfoto 2022-06-17 um 10 42 59" src="https://user-images.githubusercontent.com/274056/174261960-68868cfe-d06b-4bfb-961b-92af8b40a374.png">

**Comment by eifellovkas** [comment]
Same thing happened to me - module stopped working after working fine for a long time. Secret was not expired, creating a new one did not help. What helped was creating a new one for only 6 months (not 24 months). Hope it helps.
