### ISSUE TITLE
In depth explanation of the step: Refresh Token Generation

### ISSUE THREAD

**Issue by extremsx** [thobach/MMM-MicrosoftToDo#92]
Hi there

First of all, thank you for this great guide 

Unfortunately I run into problems trying to follow the instruction of the step:

"Refresh Token Generation" part ( https://github.com/thobach/MMM-MicrosoftToDo#refresh-token-generation-refresh-token )

Generate refresh token to allow the module to retrieve your task list going forward
1.Open Terminal app

Could you, please, provide a step by step guide what needs to be done under the step 
1.Open Terminal app

It might seam as a strait forward command for someone, who is a programmer, but for all other of us this is a hurdle that we can not overcome. 
What to open, where to write what.....

Thank you so much

**Comment by thobach** [comment]
Hi @extremsx, Sorry for the late reply. Depending on the operating system you are, there is e.g. Windows Powershell Terminal, or macOS Terminal.app.

**Comment by extremsx** [comment]
Hi Thobach

Thanks for your answer. It helped.
Unfortunately, I ran into another issue.
I installed the module.
It shows up on my mirror, but it doesn't get any data.
The client ID the client secret and the token are in the right place in the config.js
Still no data from my ToDo account.

Is there a way to test whether or not the token, client ID and secret are OK.

Thank you again

**Comment by bobbarker733** [comment]
> Hi Thobach
> 
> Thanks for your answer. It helped. Unfortunately, I ran into another issue. I installed the module. It shows up on my mirror, but it doesn't get any data. The client ID the client secret and the token are in the right place in the config.js Still no data from my ToDo account.
> 
> Is there a way to test whether or not the token, client ID and secret are OK.
> 
> Thank you again

I'm having the same issue.  Can anyone provide insight?  thanks

**Comment by thobach** [comment]
@extremsx and @bobbarker733 What logs related to the module (incl. error messages) do you see in the Magic Mirror logs (console output when you launch the Magic Mirror via ``npm run start``) and console logs (``ctrl`` + ``shift`` + ``i`` -> Console)?
