### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by PiranhaBgl** [thobach/MMM-MicrosoftToDo#95]
Hello,
since some days I d'ont have a task display
Magicmirror and modules are uptodate

if I check on pm2 logs I found:
0|MagicMirror  | [31.01.2023 11:18.01.568] [ERROR] Response {
0|MagicMirror  |   size: 0,
0|MagicMirror  |   timeout: 0,
0|MagicMirror  |   [Symbol(Body internals)]: {
0|MagicMirror  |     body: PassThrough {
0|MagicMirror  |       _readableState: [ReadableState],
0|MagicMirror  |       _events: [Object: null prototype],
0|MagicMirror  |       _eventsCount: 2,
0|MagicMirror  |       _maxListeners: undefined,
0|MagicMirror  |       _writableState: [WritableState],
0|MagicMirror  |       allowHalfOpen: true,
0|MagicMirror  |       [Symbol(kCapture)]: false,
0|MagicMirror  |       [Symbol(kCallback)]: null
0|MagicMirror  |     },
0|MagicMirror  |     disturbed: false,
0|MagicMirror  |     error: null
0|MagicMirror  |   },
0|MagicMirror  |   [Symbol(Response internals)]: {
0|MagicMirror  |     url: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
0|MagicMirror  |     status: 400,
0|MagicMirror  |     statusText: 'Bad Request',
0|MagicMirror  |     headers: Headers { [Symbol(map)]: [Object: null prototype] },
0|MagicMirror  |     counter: 0
0|MagicMirror  |   }
0|MagicMirror  | }
0|MagicMirror  | [31.01.2023 11:18.01.574] [ERROR] [MMM-MicrosoftToDo]: getTodos / get access token: https://login.microsoftonline.com/common/oauth2/v2.0/token
0|MagicMirror  | [31.01.2023 11:18.01.586] [ERROR] [MMM-MicrosoftToDo]: Error: checkFetchStatus failed with status 'Bad Request' {"size":0,"timeout":0}

**Comment by biejay** [comment]
I got the same problem unfortunately. Worked flawlessly so far.

**Comment by thobach** [comment]
I had the same issue and could resolve it by:
1. creating a new authorization code in order to 
2. generate a new refresh token, 
3. updating the refresh token in the config file, and 
4. restarting MagicMirror.

See https://github.com/thobach/MMM-MicrosoftToDo#authorization-code-generation-code and the following steps.

**Comment by biejay** [comment]
I created a new refresh token but still not luck.
The error seems to be more kind of a wrong URL or wrong format of the request? maybe the server changed how it handles incoming requests?

**Comment by biejay** [comment]
Ah nevermind. 1min later after the restart it works!

**Comment by PiranhaBgl** [comment]
Work fine

**Comment by PiranhaBgl** [comment]
thanks a lot

**Comment by jaydubya** [comment]
> 3\. updating the refresh token in the config file,

As long as your client secret hasn't expired (mine is set to 2299) the only setup you need to do is regenerate the refresh token and update the config file.  This happens about every 24 months.
