### ISSUE TITLE
Shopping list?

### ISSUE THREAD

**Issue by Megawaldi** [thobach/MMM-MicrosoftToDo#96]
Hey Developer,
i got a nice problem with your module:
I sync my Amazon Echo with Microsoft To-Do...
so i get two lists:
"Alexa to-do list" its the to do list and
"Alexa shopping list" its the shopping list.

The to do list can i sync on my mirror without any problems.
If i try so sync the shopping list, i got an "folder not found" error.
I have tryed to rename the list and sync again, without success.

Maybe there are different typs of lists. The shopping list has a different icon in Microsoft to-do.
Can you help me please to sync both typs of lists?

Greetings,
Martin

![Screenshot 2023-02-02 162827](https://user-images.githubusercontent.com/47193219/216367947-b263f78d-7e7c-4348-995a-bbae5dee31f3.jpg)

**Comment by thobach** [comment]
You can try to retrieve an access token via `curl --location --request GET 'https://login.microsoftonline.com/common/oauth2/v2.0/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=refresh_token' \
--data-urlencode 'client_id=<your-client-ID>' \
--data-urlencode 'scope=offline_access user.read tasks.readwrite tasks.read' \
--data-urlencode 'client_secret=<your-client-secret>' \
--data-urlencode 'refresh_token=<your-refresh-token>'`,

and use that to retrieve a list of lists via `curl --location --request GET 'https://graph.microsoft.com/v1.0/me/todo/lists/' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer <your-access-token>'`.

This should give you the "internal" list name of the "Alexa shopping list" that can be used in this module.

**Comment by Megawaldi** [comment]
Thank you. I got the internal Name and it worked
