### ISSUE TITLE
Does it support "Important" in ToDo?

### ISSUE THREAD

**Issue by aWilson41** [thobach/MMM-MicrosoftToDo#99]
Great Instructions!

I was curious if this supports the "Important" list in ToDo? Ofc I tried "Important" as one of the lists but no luck.

**Comment by thobach** [comment]
It is supported as an ordering criteria but not as a list itself:
`orderBy: 'createdDate', // optional parameter: 'createdDate' - order results by creation date, 'dueDate' - order results by due date, 'importance' - order result by priority (e.g. starred), default value is unordered, ordering by title is not supported anymore in API version 1`

**Comment by aWilson41** [comment]
Think it would be difficult to add myself?

I use "Important" as my like "main list". To agglomerate tasks from every other list onto it.
